# Numpy

python library provides multidimensional object

In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.2'

In [3]:
a=np.array([2,4,56,10,20,11,422])

In [4]:
a

array([  2,   4,  56,  10,  20,  11, 422])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([11,23,44],dtype=float)

array([11., 23., 44.])

In [7]:
np.array([11,23,44],dtype=bool)

array([ True,  True,  True])

In [8]:
np.array([11,23,44],dtype=complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

In [9]:
np.array([11,23,44],dtype=int)

array([11, 23, 44])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
np.arange(10,10)

array([], dtype=int32)

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10,101,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [15]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [22]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
a1=np.arange(12,dtype=float).reshape(3,4)

In [28]:
a1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [29]:
a

array([  2,   4,  56,  10,  20,  11, 422])

In [30]:
a1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [31]:
a1.ndim

2

In [32]:
a1.shape

(3, 4)

In [33]:
a1.size

12

a1.shape

In [34]:
a1.itemsize

8

In [36]:
a2=np.arange(10)

In [37]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 

In [38]:
a2.itemsize

4

In [39]:
x=np.array([33,22,2.24])
x

array([33.  , 22.  ,  2.24])

In [41]:
z1=np.arange(12).reshape(3,4)

In [42]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [44]:
z1-3

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [46]:
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [47]:
z1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [48]:
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [49]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
z1>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
z2=np.arange(10,22).reshape(3,4)

In [54]:
z2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [55]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
z2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [57]:
z1+z2

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [58]:
z1*z2

array([[  0,  11,  24,  39],
       [ 56,  75,  96, 119],
       [144, 171, 200, 231]])

In [60]:
z2-z1

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [61]:
z1/z2

array([[0.        , 0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     , 0.41176471],
       [0.44444444, 0.47368421, 0.5       , 0.52380952]])

In [62]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
z1.max()

11

In [65]:
z1.min()

0

In [66]:
z1.sum()

66

In [67]:
np.prod(z1)

0