# Numpy
used for mathematical and stastical operation its fast and memory efficient

In [1]:
import numpy as np
np.__version__

'1.25.2'

In [2]:
a=45
print(a)
print(type(a))

45
<class 'int'>


In [3]:
b=np.array(a)
b

array(45)

In [5]:
type(b)

numpy.ndarray

In [6]:
b

array(45)

In [7]:
b.ndim

0

In [8]:
b.shape

()

# 1D

In [9]:
a=[10,20,30]
b=np.array(a)
print(b)
print(type(b))

[10 20 30]
<class 'numpy.ndarray'>


In [10]:
a=np.arange(11)

In [11]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [15]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
np.zeros((2,),dtype=int)

array([0, 0])

In [18]:
np.random.randint(1,1000,100)

array([108, 182, 731, 430, 266, 191, 770, 552,  25, 670, 691, 984, 969,
       279, 397, 945, 482, 556,  45, 917, 270,  37, 446, 539, 858, 222,
       200, 255, 324, 664, 711, 531, 840,   7, 219, 117, 953, 952, 424,
        59, 597, 472, 145, 225, 600, 367, 556, 168, 824, 859, 260,  73,
       353, 398, 714, 309, 338,  93, 252, 542, 261, 547, 530, 917, 624,
       783, 822, 758, 234, 285, 379, 740, 552,  70, 692, 803,  65,  84,
       751,  56, 166, 352, 166, 906, 240, 402, 256, 461, 813, 924, 851,
       469, 947, 194, 612, 450,  89,  35, 722, 736])

In [19]:
np.random.randint(1,1000,100)

array([587, 251, 413, 438,  90, 693, 830, 836, 995, 517, 231, 375, 949,
       748, 513,  73, 145, 677, 612, 290, 718, 930, 931, 972, 565,  78,
       204,  20, 332, 781, 457, 183, 251, 330, 418, 748,  85, 501, 385,
       420, 142, 803, 761, 569, 259, 408, 313, 804, 921, 310, 176,  96,
       139, 327, 562, 296, 695, 565, 956, 825, 126, 275, 269, 447, 269,
       170, 748, 544, 215, 532, 965, 726, 560, 371, 120, 174, 893,  42,
       786, 103, 835,  89, 115, 713, 596, 636, 666, 669, 655, 337, 849,
       396, 737, 900, 263, 156, 640, 749, 555, 871])

In [20]:
np.random.randint(1,1000,100)

array([497, 661, 142, 554, 796, 666, 873, 560, 483, 553, 151, 640, 859,
       352,  95, 471, 778, 606, 215, 818, 214,  26, 762,  25, 776, 451,
        12, 707, 354, 553, 839, 174, 532, 743, 482, 729, 150, 852, 258,
       897, 437, 466, 604,  39,  15, 989, 401,  64, 374, 682,  63, 380,
       141, 419, 291, 574, 353, 971, 978, 627, 293, 560, 145, 841, 997,
       738, 629, 971, 834, 314, 130, 309, 974, 472, 257, 587, 555,  15,
       421, 697, 320,  60, 827, 508, 130, 572, 398, 818,  74, 286, 656,
       649, 424, 284, 434, 157, 713, 586, 460, 118])

In [21]:
np.random.randint(1,1000,100)

array([882, 536, 497, 247, 854,   9, 773, 858,  86, 726, 501, 298, 849,
       552, 177, 321, 962, 343, 785, 904, 709, 107, 505, 453, 236, 894,
       647, 838, 467, 976, 233, 437, 834, 623, 339, 448, 878,  89, 151,
       403, 243, 982, 111, 712, 653, 456, 500,  43, 496, 938, 727, 945,
       383,  86,  70, 530, 382, 725,  20, 152, 323,  22, 459, 531, 606,
       590, 551, 274, 455, 139, 318, 768, 673, 532, 498, 961, 180, 355,
        11, 933, 837, 524, 753, 985, 522, 205, 549, 510, 419, 884, 375,
       365, 485, 772, 706,  82, 798, 897, 962, 847])

In [22]:
a=np.arange(10,51,10)
a

array([10, 20, 30, 40, 50])

In [23]:
a[0]

10

In [24]:
a[-1]

50

In [25]:
a[1:5:2]

array([20, 40])

In [26]:
a[-1:-4:-1]

array([50, 40, 30])

In [28]:
a[[0,1,2]]

array([10, 20, 30])

In [29]:
a

array([10, 20, 30, 40, 50])

In [32]:
a=np.array([45,46,42,20,47])
a[a%2==0]

array([46, 42, 20])

In [34]:
b=np.append(a,1000)

In [35]:
a

array([45, 46, 42, 20, 47])

In [36]:
b

array([  45,   46,   42,   20,   47, 1000])

In [37]:
b=np.append(a,[10,20,30,40])

In [38]:
b

array([45, 46, 42, 20, 47, 10, 20, 30, 40])

In [39]:
a[0]

45

In [40]:
a[0]=99

In [41]:
a

array([99, 46, 42, 20, 47])

In [42]:
a[[0,1]]=15

In [43]:
a

array([15, 15, 42, 20, 47])

In [46]:
a[[0,1]]=[90,100]
a

array([ 90, 100,  42,  20,  47])

In [51]:
a3=np.delete(a,[0,1])
print(a3)

[42 20 47]


In [52]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [53]:
b=a.copy()

In [54]:
b

array([1, 2, 3, 4])

In [55]:
b[0]

1

In [57]:
print(id(a))
print(id(a))

1921470684720
1921470684720


In [60]:
a=np.array([10,11,2,3,5])
b=np.sort(a)
b

array([ 2,  3,  5, 10, 11])

In [63]:
a=np.array([10,11,2,3,5])
a

array([10, 11,  2,  3,  5])

In [62]:
a+1

array([11, 12,  3,  4,  6])

In [66]:
b=a*2
b

array([20, 22,  4,  6, 10])

In [67]:
a+b

array([30, 33,  6,  9, 15])

In [68]:
a-b

array([-10, -11,  -2,  -3,  -5])

In [69]:
a*b

array([200, 242,   8,  18,  50])

In [72]:
a

array([10, 11,  2,  3,  5])

In [73]:
b

array([20, 22,  4,  6, 10])

In [74]:
a==b

array([False, False, False, False, False])

In [75]:
a>b

array([False, False, False, False, False])

In [76]:
b<a

array([False, False, False, False, False])

In [77]:
a<b

array([ True,  True,  True,  True,  True])

In [78]:
np.array_equal(a,b)

False

In [81]:
np.array_equal(b,a)

False

In [82]:
np.exp(a)

array([2.20264658e+04, 5.98741417e+04, 7.38905610e+00, 2.00855369e+01,
       1.48413159e+02])

In [83]:
np.log(a)

array([2.30258509, 2.39789527, 0.69314718, 1.09861229, 1.60943791])

In [84]:
b=np.array([[0,1,2,3],[4,5,6,7]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [85]:
b.ndim

2

In [86]:
b.shape

(2, 4)

In [87]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [89]:
np.ones((40,40))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [90]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
np.diag([1,2,4,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]])

In [93]:
a=np.array([[10,20,30],[40,50,60],[70,80,80]])

In [94]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 80]])

In [95]:
a[0] #all coloumn by default

array([10, 20, 30])

In [96]:
a[0][1]

20

In [97]:
a[2][2]

80

In [98]:
a[1]=[100,200,300]

In [99]:
a

array([[ 10,  20,  30],
       [100, 200, 300],
       [ 70,  80,  80]])

In [100]:
a[0,2]=500

In [101]:
a

array([[ 10,  20, 500],
       [100, 200, 300],
       [ 70,  80,  80]])

In [103]:
a[1,2]=600

In [104]:
a

array([[ 10,  20, 500],
       [100, 200, 600],
       [ 70,  80,  80]])

In [105]:
a

array([[ 10,  20, 500],
       [100, 200, 600],
       [ 70,  80,  80]])

In [112]:
#Flattening:converting array to 1D array
b=a.ravel()
type(b)
b.shape

(9,)

In [108]:
b.reshape(3,3)

array([[ 10,  20, 500],
       [100, 200, 600],
       [ 70,  80,  80]])

In [113]:
type(b)
print(b.shape)

(9,)


In [114]:
c=a.T

In [115]:
c

array([[ 10, 100,  70],
       [ 20, 200,  80],
       [500, 600,  80]])

In [116]:
#sorting
a=np.array([[10,20,30],[40,50,60],[70,80,80]])

In [117]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 80]])

In [120]:
b=np.sort(a,axis=0)

In [121]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 80]])

In [122]:
# Creating a 2D array (list of lists)
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])



In [123]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 80]])

In [125]:
a+arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 89]])

In [126]:
a*arr

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 720]])

In [127]:
np.matmul(a,arr)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [ 950, 1180, 1410]])

In [132]:
# np.concatnate((a,b),axis=0)